source 'https://github.com/CocoaPods/Specs.git'

target 'RaisinToast', :exclusive => true do
  pod "RaisinToast", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RaisinToast", :path => "../"

end
